import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // enable variable
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="site-frame">
          <nav className="left-nav" aria-label="Primary">
            <ul className="nav-list">
              <li className="nav-item selected">Portfolio</li>
              <li className="nav-item">About</li>
              <li className="nav-item">Projects</li>
              <li className="nav-item">Resume</li>
              <li className="nav-item">Contact</li>
            </ul>
          </nav>

          <main className="content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
