import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // enable variable
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="site-frame">
          <div className="border-cuts">
            <span className="cut top c1" />
            <span className="cut top c2" />
            <span className="cut top c3" />
            <span className="cut top c4" />

            <span className="cut right c1" />
            <span className="cut right c2" />
            <span className="cut right c3" />
            <span className="cut right c4" />

            <span className="cut bottom c1" />
            <span className="cut bottom c2" />
            <span className="cut bottom c3" />
            <span className="cut bottom c4" />

            <span className="cut left c1" />
            <span className="cut left c2" />
            <span className="cut left c3" />
            <span className="cut left c4" />
          </div>
          <nav className="left-nav" aria-label="Primary">
            <ul className="nav-list">
              <li className="nav-item selected" id="portfolio-nav">Portfolio</li>
              <li className="nav-item" id="about-nav">About</li>
              <li className="nav-item">Projects</li>
              <li className="nav-item">Resume</li>
              <li className="nav-item">Contact</li>
            </ul>
          </nav>
          <script dangerouslySetInnerHTML={{__html: `
            (function(){
              var about = document.getElementById('about-nav');
              var portfolio = document.getElementById('portfolio-nav');
              if(about) about.addEventListener('click', function(e){ e.preventDefault(); window.dispatchEvent(new CustomEvent('setPageState', { detail: { state: 'about' } })); });
              if(portfolio) portfolio.addEventListener('click', function(e){ e.preventDefault(); window.dispatchEvent(new CustomEvent('setPageState', { detail: { state: 'portfolio' } })); });
            })();
          `}} />

          <main className="content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
